#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "prepare dist/index.js ..."
# keep the original file name
cp setImmediate.js dist/
# and also release a `index.js`
cp setImmediate.js dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "done."
